server:
  port: 8001
  
spring:  application:    name: cloud-hystrix-payment-service
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      #集群      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      #单机
      defaultZone: http://localhost:7001/eureka
  instance:    instance-id: ${spring.application.name}:${server.port}
