server:
  port: 7001
  
eureka:  instance:    hostname: eureka:7001
  client:    register-with-eureka: false
    fetch-registry: false
    service-url:
      #集群      #defaultZone: http://127.0.0.1:7002/eureka/
      #单机
      defaultZone: http://127.0.0.1:7001/eureka/  #server:    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000