server:
  port: 8002
  
spring:  application:    name: cloud-payment-service
      datasource:    url: jdbc:mysql://127.0.0.1:3306/cloud2?serverTimezone=GMT%2B8
    username: root
    password: 1234
    
mybatis:  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yang.entity

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}